import React, { useState } from 'react';
import {
  Settings,
  User,
  Calendar,
  Download,
  FileText,
  Sparkles,
  CheckCircle,
  Clock,
  ShieldCheck
} from 'lucide-react';
import { UserProfile, Project } from '../types';

interface SettingsViewProps {
  profile: UserProfile | null;
  activeProject: Project | null;
  onOpenOnboarding: () => void;
  onUpdateDeadline: (newDeadline: string) => void;
}

export const SettingsView: React.FC<SettingsViewProps> = ({
  profile,
  activeProject,
  onOpenOnboarding,
  onUpdateDeadline
}) => {
  const [deadlineInput, setDeadlineInput] = useState(
    activeProject?.deadline ? activeProject.deadline.split('T')[0] : ''
  );
  const [isSaved, setIsSaved] = useState(false);

  const handleSaveDeadline = (e: React.FormEvent) => {
    e.preventDefault();
    if (deadlineInput) {
      onUpdateDeadline(new Date(deadlineInput).toISOString());
      setIsSaved(true);
      setTimeout(() => setIsSaved(false), 2500);
    }
  };

  const handleExportReport = () => {
    if (!activeProject) return;
    const content = `# IEEE CAPSTONE PROJECT REPORT: ${activeProject.title}
Generated by BUILDflow AI

## Problem Statement
${activeProject.problem}

## Solution Overview
${activeProject.solution}

## Technology Stack
${activeProject.techStack.join(', ')}

## Execution Status
- Current Phase: ${activeProject.currentPhase}
- Completion Progress: ${activeProject.progress}%
- Health Status: ${activeProject.health}
- Target Deadline: ${activeProject.deadline}

---
Certified for Final-Year Examination Committee Review. Generated with BUILDflow AI.`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeProject.title.replace(/[^a-zA-Z0-9]/g, '_')}_Report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto pb-12">
      <div>
        <span className="text-[10px] font-bold uppercase tracking-wider text-[#22D3EE]">
          PREFERENCES & EXPORTS
        </span>
        <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-[#F8FAFC] mt-0.5">
          Settings & Capstone Controls
        </h1>
        <p className="text-sm text-[#94A3B8] mt-1">
          Configure student profile, deadline targets, and generate IEEE project export reports.
        </p>
      </div>

      {/* Student Profile Card */}
      <div className="p-6 rounded-2xl bg-[#111827] border border-[#263247] space-y-4">
        <div className="flex items-center justify-between pb-4 border-b border-[#263247]">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 rounded-xl bg-gradient-to-tr from-[#6C63FF] to-[#22D3EE] flex items-center justify-center text-white font-bold text-lg shadow-[0_0_15px_rgba(108,99,255,0.3)]">
              {(profile?.name || 'S')[0]}
            </div>
            <div>
              <h3 className="text-base font-bold text-[#F8FAFC]">
                {profile?.name || 'Student Lead'}
              </h3>
              <p className="text-xs text-[#94A3B8]">
                {profile?.email || 'student@university.edu'}
              </p>
            </div>
          </div>

          <button
            id="settings-edit-profile-btn"
            onClick={onOpenOnboarding}
            className="px-4 py-2 rounded-xl bg-[#0D1220] border border-[#263247] hover:border-[#6C63FF]/50 text-[#CBD5E1] hover:text-[#F8FAFC] text-xs font-semibold transition-colors"
          >
            Edit Profile & Skills
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div>
            <span className="text-[#94A3B8] font-medium block mb-1.5">Registered Technical Skills:</span>
            <div className="flex flex-wrap gap-1.5">
              {profile?.skills.map(s => (
                <span key={s} className="px-2 py-0.5 rounded-md bg-[#0D1220] border border-[#263247] text-[#22D3EE]">
                  {s}
                </span>
              ))}
            </div>
          </div>

          <div>
            <span className="text-[#94A3B8] font-medium block mb-1.5">Academic Interests:</span>
            <div className="flex flex-wrap gap-1.5">
              {profile?.interests.map(i => (
                <span key={i} className="px-2 py-0.5 rounded-md bg-[#0D1220] border border-[#263247] text-[#6C63FF]">
                  {i}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Deadline Calibration */}
      {activeProject && (
        <form onSubmit={handleSaveDeadline} className="p-6 rounded-2xl bg-[#111827] border border-[#263247] space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-[#22D3EE]">
            Calibrate Project Viva Deadline
          </h3>
          <p className="text-xs text-[#94A3B8]">
            Adjusting this date recalculates the AI Health status (ON TRACK / AT RISK / BEHIND) and daily velocity targets.
          </p>

          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
            <input
              id="settings-deadline-input"
              type="date"
              value={deadlineInput}
              onChange={e => setDeadlineInput(e.target.value)}
              className="px-3.5 py-2.5 rounded-xl bg-[#0D1220] border border-[#263247] text-xs text-[#F8FAFC] focus:outline-none focus:border-[#6C63FF]"
            />
            <button
              id="settings-save-deadline-btn"
              type="submit"
              className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-[#6C63FF] to-[#22D3EE] text-white text-xs font-semibold hover:opacity-95 transition-all shadow-sm"
            >
              Update Deadline
            </button>
            {isSaved && (
              <span className="text-xs font-semibold text-[#34D399] flex items-center gap-1">
                <CheckCircle className="h-4 w-4" />
                <span>Updated and recalculated</span>
              </span>
            )}
          </div>
        </form>
      )}

      {/* Export Report */}
      {activeProject && (
        <div className="p-6 rounded-2xl bg-[#111827] border border-[#263247] flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h3 className="text-sm font-bold text-[#F8FAFC]">
              Export IEEE Capstone Dissertation Report
            </h3>
            <p className="text-xs text-[#94A3B8] mt-1">
              Download complete structured documentation formatted for final presentation and plagiarism checks.
            </p>
          </div>

          <button
            id="settings-export-report-btn"
            onClick={handleExportReport}
            className="px-4 py-2.5 rounded-xl bg-[#0D1220] hover:bg-[#172033] border border-[#263247] hover:border-[#22D3EE]/40 text-[#22D3EE] font-semibold text-xs flex items-center gap-2 transition-colors shrink-0"
          >
            <Download className="h-4 w-4" />
            <span>Export Report (.md)</span>
          </button>
        </div>
      )}
    </div>
  );
};
